import os
import pyspark
from pyspark.sql import SparkSession
import pyspark.sql.functions as F
from pyspark.ml.feature import VectorAssembler
from pyspark.ml.regression import LinearRegression
from pyspark.ml.evaluation import RegressionEvaluator

# suppress spark logs for cleaner output
import logging
logging.getLogger("py4j").setLevel(logging.ERROR)

from main import app

def generate_stats_from_df(df):
    numeric_cols = [f.name for f in df.schema.fields if isinstance(f.dataType, (pyspark.sql.types.DoubleType, pyspark.sql.types.IntegerType, pyspark.sql.types.FloatType, pyspark.sql.types.LongType))]
    stats = {}
    for c in numeric_cols:
        # compute mean, min, max
        col_stats = df.select(
            F.mean(F.col(c)).alias('mean'),
            F.min(F.col(c)).alias('min'),
            F.max(F.col(c)).alias('max')
        ).collect()[0]
        stats[f"{c}_mean"] = float(col_stats['mean']) if col_stats['mean'] is not None else 0.0
        stats[f"{c}_min"] = float(col_stats['min']) if col_stats['min'] is not None else 0.0
        stats[f"{c}_max"] = float(col_stats['max']) if col_stats['max'] is not None else 0.0
    return stats

def run_test():
    spark = SparkSession.builder \
        .appName("TaxiFlowTest") \
        .config("spark.driver.memory", "2g") \
        .getOrCreate()
    
    spark.sparkContext.setLogLevel("ERROR")
    
    print("Loading datasets...")
    # Load the mock CSVs
    df_jan = spark.read.csv("taxi_jan.csv", header=True, inferSchema=True)
    df_feb = spark.read.csv("taxi_feb.csv", header=True, inferSchema=True)
    
    # Target: total_amount. Features: trip_distance, fare_amount, tip_amount
    cols_to_use = ["trip_distance", "fare_amount", "tip_amount", "total_amount"]
    
    # Cast to double safely
    for c in cols_to_use:
        df_jan = df_jan.withColumn(c, F.col(c).cast("double"))
        df_feb = df_feb.withColumn(c, F.col(c).cast("double"))
        
    df_jan = df_jan.select(*cols_to_use).dropna()
    df_feb = df_feb.select(*cols_to_use).dropna()
    
    print("Computing Jan stats (Mock Data Analysis)...")
    jan_stats = generate_stats_from_df(df_jan)
    
    print("\n========== SCENARIO 1: INITIAL TRAINING (JAN) ==========")
    initial_state = {
        "scenario": "initial_training",
        "dataset_stats": {
            "columns": df_jan.columns,
            "jan_stats": jan_stats
        },
        "evaluation_metrics": None
    }
    
    final_jan_state = app.invoke(initial_state)
    print("\n[Output] Initial Training State generated by LangGraph Workflow:")
    if final_jan_state.get("feature_engineering_plan"):
        print(final_jan_state["feature_engineering_plan"].model_dump())
    
    print("\n-----------------------------------------------------------")
    print("Training PySpark Linear Regression on Jan data...")
    assembler = VectorAssembler(inputCols=["trip_distance", "fare_amount", "tip_amount"], outputCol="features")
    train_data = assembler.transform(df_jan)
    lr = LinearRegression(featuresCol="features", labelCol="total_amount")
    lr_model = lr.fit(train_data)
    
    print("Evaluating model on Feb data...")
    test_data = assembler.transform(df_feb)
    predictions = lr_model.transform(test_data)
    
    evaluator_rmse = RegressionEvaluator(labelCol="total_amount", predictionCol="prediction", metricName="rmse")
    evaluator_r2 = RegressionEvaluator(labelCol="total_amount", predictionCol="prediction", metricName="r2")
    evaluator_mae = RegressionEvaluator(labelCol="total_amount", predictionCol="prediction", metricName="mae")
    
    rmse = evaluator_rmse.evaluate(predictions)
    r2 = evaluator_r2.evaluate(predictions)
    mae = evaluator_mae.evaluate(predictions)
    
    print(f"Metrics (PySpark Evaluation): RMSE={rmse:.2f}, R2={r2:.2f}, MAE={mae:.2f}")
    
    print("\nComputing Feb stats (Mock Data Analysis)...")
    feb_stats = generate_stats_from_df(df_feb)
    
    print("\n========== SCENARIO 2: MARCH MONITORING (FEB DATA) ==========")
    monitoring_state = {
        "scenario": "march_monitoring",
        "dataset_stats": {
            "columns": df_feb.columns,
            "jan_stats": jan_stats,
            "feb_stats": feb_stats
        },
        "evaluation_metrics": {
            "RMSE": rmse,
            "R2": r2,
            "MAE": mae
        }
    }
    
    final_feb_state = app.invoke(monitoring_state)
    print("\n[Output] Monitoring State generated by LangGraph Workflow:")
    if final_feb_state.get("drift_report"):
        print("Drift Report: ", final_feb_state["drift_report"].model_dump())
    if final_feb_state.get("validation_report"):
        print("Validation Report: ", final_feb_state["validation_report"].model_dump())
        print("Retrain decision given to PySpark Workflow: ", final_feb_state["validation_report"].requires_retraining)

    spark.stop()

if __name__ == "__main__":
    run_test()
